// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace MycoreApp.Models;

public partial class onlineshoppingdbContext : DbContext
{
    public onlineshoppingdbContext()
    {
    }

    public onlineshoppingdbContext(DbContextOptions<onlineshoppingdbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<Registertbl> Registertbls { get; set; }

    public virtual DbSet<Userorder> Userorders { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=WKSPUN05GTR0907;Initial Catalog=onlineshoppingdb;Integrated Security=True; TrustServerCertificate=true");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.Pid).HasName("PK__products__DD37D91A98BC46CC");

            entity.ToTable("products");

            entity.Property(e => e.Pid)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("pid");
            entity.Property(e => e.Description)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("description");
            entity.Property(e => e.Pimage)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("pimage");
            entity.Property(e => e.Pname)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("pname");
            entity.Property(e => e.Price).HasColumnName("price");
        });

        modelBuilder.Entity<Registertbl>(entity =>
        {
            entity.HasKey(e => e.Uname).HasName("PK__Register__C7D2484FE2A66409");

            entity.ToTable("Registertbl");

            entity.Property(e => e.Uname)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("uname");
            entity.Property(e => e.Age).HasColumnName("age");
            entity.Property(e => e.Email)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("email");
            entity.Property(e => e.Nationality)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("nationality");
            entity.Property(e => e.Password)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("password");
        });

        modelBuilder.Entity<Userorder>(entity =>
        {
            entity.HasKey(e => e.Tranid).HasName("PK__userorde__9A599E035019401A");

            entity.ToTable("userorders");

            entity.Property(e => e.Tranid)
                .ValueGeneratedNever()
                .HasColumnName("tranid");
            entity.Property(e => e.Pid)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("pid");
            entity.Property(e => e.Qty).HasColumnName("qty");
            entity.Property(e => e.Transdate)
                .HasColumnType("date")
                .HasColumnName("transdate");
            entity.Property(e => e.Username)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("username");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}