// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MycoreApp.Models;

public partial class Registertbl
{
    public string Uname { get; set; }

    public string Password { get; set; }

    public int? Age { get; set; }

    public string Email { get; set; }

    public string Nationality { get; set; }
}